### PR TITLE
Zephyr: add support for DIS tests

### PR DESCRIPTION
**Pull request by KKopyscinski**

### CODE REVIEW

**Comment by KKopyscinski** [comment]
All tests are passing

<details>

 1/15   DIS     DIS/SR/SD/BV-01-C    PASS            27.807                  
 2/15   DIS     DIS/SR/DEC/BV-01-C   PASS            26.917                  
 3/15   DIS     DIS/SR/DEC/BV-02-C   PASS            27.283                  
 4/15   DIS     DIS/SR/DEC/BV-03-C   PASS            27.437                  
 5/15   DIS     DIS/SR/DEC/BV-04-C   PASS            27.284                  
 6/15   DIS     DIS/SR/DEC/BV-05-C   PASS            28.002                  
 7/15   DIS     DIS/SR/DEC/BV-06-C   PASS            27.825                  
 8/15   DIS     DIS/SR/DEC/BV-09-C   PASS            27.037                  
 9/15   DIS     DIS/SR/CR/BV-01-C    PASS            28.209                  
10/15   DIS     DIS/SR/CR/BV-02-C    PASS            27.349                  
11/15   DIS     DIS/SR/CR/BV-03-C    PASS            26.995                  
12/15   DIS     DIS/SR/CR/BV-04-C    PASS            29.0                  
13/15   DIS     DIS/SR/CR/BV-05-C    PASS            27.005                  
14/15   DIS     DIS/SR/CR/BV-06-C    PASS            28.016                  
15/15   DIS     DIS/SR/CR/BV-09-C    PASS            27.601   

</details>

**Comment by KKopyscinski** [comment]
removed unused code from `dis_wid.py`

**Comment by KKopyscinski** [comment]
Adjusted Copyrights

**Review by michal-narajowski — APPROVED** [review]
LGTM

**Pull request merged**
